### PR TITLE
Scoped IOptionsSnapshot<Policy> instead of Singleton IOptions<Policy>

### PR DESCRIPTION
**Pull request by fileman**
#4

### CODE REVIEW

**Review by leastprivilege — CHANGES_REQUESTED** [review]
I still like to have the options class in DI - can you add line 26 back - but use the options monitor and a transient?

**Comment by fileman** [comment]
Sorry I forgot to uncomment it

**Comment by fileman** [comment]
I prefer Scoped but with this lifetime I got this error `Cannot consume scoped service 'PolicyServer.Local.Policy' from singleton 'Microsoft.AspNetCore.Mvc.Infrastructure.IActionDescriptorCollectionProvider'.`
However reading [this](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options#reload-configuration-data-with-ioptionssnapshot) seem that asp.net core 2.0 IOptionMonitor is scoped.
Instead with Singleton lifetime data wasn't updated

**Review by fileman — COMMENTED** [review]
rollback to initial code with only IOptionsMonitor instead of IOptions

**Comment by leastprivilege** [comment]
I am getting the same error and this is weird.. Anyways - I removed the DI magic altogether here

https://github.com/PolicyServer/PolicyServer.Local/commit/510c06bac2c6999bfcfaddb318c9a334fe31a81e

OK?

**Comment by fileman** [comment]
Can you read my last comment at #4, because I have not-committed code with DI and no error, but I don't know if is better scoped or transient

**Comment by brockallen** [comment]
fix manually, thanks.

**Pull request closed without merging**
