### PR TITLE
Update PolicyResult Class for better extensibility

### PR DESCRIPTION
**Pull request by noufionline**
This change will be a welcome change for those who wants to implement a Custom PolicyServerClient Implementation.

### CODE REVIEW

**Comment by leastprivilege** [comment]
Use case?

**Comment by noufionline** [comment]
Creating a custom implementation of Policyserver client which can connect to a different data store and pull claims. This will help to register a different implementation of PolicyServer client in the DI Container

**Comment by leastprivilege** [comment]
The Local version is hard-coded to use the ASP.NET Core config system - if you want to extend that, create a provider for that.

**Comment by noufionline** [comment]
You mean inheriting from  AuthorizationPolicyProvider Class? I actually wanted to create a custom PolicerverClient and register with DI so that it can fetch claims from a database. I tried it but since the PolicyResult properties internal I could not assign my permissions and roles.

Hope I was clear with my requirements.

**Comment by noufionline** [comment]
@leastprivilege @Jenan 
Sorry to ask you? Why this pull request was not accepted?

**Pull request closed without merging**
